#!/bin/bash
# The logic to stop your application should be put in this script.

# kill the server through the pidfile
kill `ps -ef | grep 'unicorn master' | awk '{ print $2 }'` > /dev/null 2>&1

exit 0
